export const REQUEST_USER_SIGNIN = "REQUEST_USER_SIGNIN";
export const FAIL_USER_SIGNIN = "FAIL_USER_SIGNIN";
export const SUCCESS_USER_SIGNIN = "SUCCESS_USER_SIGNIN";
export const USER_SIGNOUT = "USER_SIGNOUT";